"""Add ficha_medica columns to Socio

Revision ID: 0736d0c6a16f
Revises: a6987621f16d
Create Date: 2025-03-28 11:02:23.248470

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0736d0c6a16f'
down_revision = 'a6987621f16d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('username')

    op.drop_table('user')
    with op.batch_alter_table('socio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ficha_medica', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fecha_ultima_revision_medica', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('fecha_proxima_revision_medica', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('socio', schema=None) as batch_op:
        batch_op.drop_column('fecha_proxima_revision_medica')
        batch_op.drop_column('fecha_ultima_revision_medica')
        batch_op.drop_column('ficha_medica')

    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=True)

    # ### end Alembic commands ###
